name: ips-dev
services:
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - .env
    depends_on:
      - convert
      - signal

  convert:
    build:
      context: ./services/convert
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/convert:/app
    ports:
      - 8001:8000
    env_file:
      - .env
    
  signal:
    build:
      context: ./services/signal
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/signal:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379